#!/usr/bin/env python3
"""Writes src/mi_tables.inc: the tables of the PLAITS machine (src/plaits.inc,
docs/PLAITS.md). Rerun after changing them; CI checks that the file is up to
date.

The waveshaper, wavefolder and FM-ratio tables are computed with the formulas
of Mutable Instruments Plaits (plaits/resources/lookup_tables.py,
Copyright 2016 Emilie Gillet, MIT licence - the notice is in docs/PLAITS.md),
rescaled to integers. Everything else is ours.

All rates are the render's: 96 kHz, 64-sample blocks.
  mi_sin      256 longs: sin(2 pi k/256) x 32767 in the high word, the step to
              the next entry in the low word (linear interpolation)
  mi_ws       Plaits' five waveshapers (inverse tan, inverse sin, linear, bump,
              double bump) and a sentinel copy of the last, 257 words each, Q15
  mi_fold     Plaits' wavefolder (lut_fold + 1), 514 words, Q15
  mi_fmq      Plaits' FM ratio quantizer (lut_fm_frequency_quantizer), as
              ratios, 130 words, Q12
  mi_semi     the phase increment (Q32 at 96 kHz) of MIDI notes 0..12
  mi_e2       2^(k/12) for k = 0..12, Q14
  mi_chord    Plaits' eleven chords (chord_bank.cc), four ratios each, Q12
  mi_chn      ...and how many notes the arpeggiator walks in each
"""
import math, os

FS = 96000.0
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'mi_tables.inc')

# ---- sine: value and step, for linear interpolation -------------------------
sv = [round(32767 * math.sin(2 * math.pi * k / 256)) for k in range(257)]
sin_l = [((sv[k] & 0xffff) << 16) | ((sv[k + 1] - sv[k]) & 0xffff) for k in range(256)]

# ---- Plaits' waveshapers (from Tides) ---------------------------------------
N = 128
xs = [i / N for i in range(N + 1)]
tanv = [math.atan(8 * math.cos(math.pi * x)) for x in xs]
scale = max(tanv)
linear = xs
bump = [(1 - math.cos(math.pi * x * 1.5)) * (1 - math.cos(math.pi * min(1.0, 4 - 4 * x))) / 4.5
        for x in xs]
double_bump = [math.sin(math.pi * x * 1.5) for x in xs]
inverse_sin = [math.acos(1 - 2 * x) / math.pi for x in xs]
inverse_tan = [math.acos(math.tan(scale * (1 - 2 * x)) / 8) / math.pi for x in xs]


def flip(v):
    w = [-a for a in v[N:0:-1]] + list(v)
    return [round(a * 32767) for a in w]


ws = [flip(t) for t in (inverse_tan, inverse_sin, linear, bump, double_bump, double_bump)]
assert all(len(t) == 257 for t in ws)

# ---- Plaits' wavefolder -------------------------------------------------------
M = 512
fx = [i / (M / 2) - 1 for i in range(M + 4)]
fx[-1] = fx[-2]
fold = []
for x in fx:
    w = math.exp(-x * x * 4) ** 2
    fold.append(math.sin(8 * math.pi * x) * w + math.atan(3 * x) * (1 - w))
fm_ = max(abs(a) for a in fold)
fold = [round(32767 * a / fm_) for a in fold][1:515]      # lut_fold + 1, 514 entries
assert len(fold) == 514

# ---- Plaits' FM ratio quantizer -----------------------------------------------
ratios = [0.5, 0.5 * 2 ** (16 / 1200), math.sqrt(2) / 2, math.pi / 4, 1.0, 2 ** (16 / 1200),
          math.sqrt(2), math.pi / 2, 7 / 4, 2, 2 * 2 ** (16 / 1200), 9 / 4, 11 / 4,
          2 * math.sqrt(2), 3, math.pi, math.sqrt(3) * 2, 4, math.sqrt(2) * 3,
          math.pi * 3 / 2, 5, math.sqrt(2) * 4, 8]
sc = []
for r in ratios:
    s = 12 * math.log2(r)
    sc += [s, s, s]
target = 2 ** math.ceil(math.log2(len(sc)))
while len(sc) < target:
    d = [b - a for a, b in zip(sc, sc[1:])]
    g = d.index(max(d))
    sc = sc[:g + 1] + [(sc[g] + sc[g + 1]) / 2] + sc[g + 1:]
sc += [sc[-1], sc[-1]]
fmq = [round(4096 * 2 ** (s / 12)) for s in sc]
assert len(fmq) == 130 and max(fmq) <= 32768

# ---- pitch ----------------------------------------------------------------------
semi = [round(440 * 2 ** ((k - 69) / 12) / FS * 2 ** 32) for k in range(13)]
e2 = [round(16384 * 2 ** (k / 12)) for k in range(13)]

# ---- Plaits' chords and the arpeggiator's note counts --------------------------------
chords = [(0, .01, 11.99, 12), (0, 7, 7.01, 12), (0, 5, 7, 12), (0, 3, 7, 12), (0, 3, 7, 10),
          (0, 3, 10, 14), (0, 3, 10, 17), (0, 2, 9, 16), (0, 4, 11, 14), (0, 4, 7, 11),
          (0, 4, 7, 12)]
chq = [round(4096 * 2 ** (s / 12)) for c in chords for s in c]
chn = [sum(1 for s in c if s not in (.01, 7.01, 11.99, 12)) for c in chords]
assert all(1 <= n <= 4 for n in chn)


def rows(vals, per, d='.long'):
    return [f"    {d} " + ", ".join(map(str, vals[i:i + per])) for i in range(0, len(vals), per)]


L = ["",
     "| mi_tables.inc - generated by tools/gen_mi_tables.py. Do not edit.",
     "| Waveshaper, folder and FM-ratio tables: formulas of Mutable Instruments",
     "| Plaits, (c) 2016 Emilie Gillet, MIT licence (docs/PLAITS.md).",
     "    .align 2",
     "mi_sin:                   | sin x 32767 << 16 | step to the next"]
L += rows([f"0x{v:08x}" for v in sin_l], 8)
L.append("mi_semi:                  | MIDI notes 0..12: increment, Q32 at 96 kHz")
L += rows(semi, 7)
L.append("mi_ws:                    | Plaits' waveshapers, 6 x 257, Q15")
for t in ws:
    L += rows(t, 16, '.word')
L.append("mi_fold:                  | Plaits' wavefolder (lut_fold + 1), Q15")
L += rows(fold, 16, '.word')
L.append("mi_fmq:                   | Plaits' FM ratio quantizer, ratios Q12")
L += rows(fmq, 16, '.word')
L.append("mi_e2:                    | 2^(k/12), Q14")
L += rows(e2, 13, '.word')
L.append("mi_chord:                 | Plaits' chords: four ratios each, Q12")
L += rows(chq, 4, '.word')
L.append("mi_chn:                   | notes the arpeggiator walks, per chord")
L += rows(chn, 11, '.byte')
L += ["    .align 2", ""]
open(out, 'w').write("\n".join(L))
print(f"wrote {os.path.relpath(out)}")
