#!/usr/bin/env python3
"""Writes src/va_tables.inc: the VA machine's OSC 2 tuning table.
Rerun after changing the curve; CI checks that the file is up to date.

DETUNE dial 0..127 -> OSC 2 frequency ratio, Q16 (65536 = unison).
  x = (d - 64) / 64 below the centre, (d - 64) / 63 above it, so 0 and 127
  are exactly -12 and +12 semitones;
  semitones = 12 * (0.1 x + 0.9 x^3): fine near the centre (65 is +1.9
  cents, 68 - the default - +7.9 cents, 80 about half a semitone) and an
  octave at either end.
"""
import os

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..',
                   'src', 'va_tables.inc')


def semis(d):
    x = (d - 64) / (64 if d < 64 else 63)
    return 12 * (0.1 * x + 0.9 * x ** 3)


ratio = [round(65536 * 2 ** (semis(d) / 12)) for d in range(128)]
assert ratio[64] == 65536 and ratio[0] == 32768 and ratio[127] == 131072
assert all(a < b for a, b in zip(ratio, ratio[1:])), "the curve must rise"

# The first line is blank: GNU as can misread an included file's first line.
L = ["",
     "| va_tables.inc - generated by tools/gen_va_tables.py. Do not edit.",
     "| DETUNE dial 0..127 -> OSC 2 ratio, Q16; 64 = unison, 0 / 127 = -/+ 1 octave",
     "    .align 4",
     "va_det_tab:"]
L += ["    .long " + ",".join(map(str, ratio[i:i + 8])) for i in range(0, 128, 8)]
open(out, 'w').write("\n".join(L) + "\n")
print(f"wrote {out}")
