#!/usr/bin/env python3
"""Writes src/drum_tables.inc: constants and tables for the VA KICK, VA SNARE
and VA HIHAT machines (src/drums.inc, docs/DRUMS.md). Rerun after changing
them; CI checks that the file is up to date.

All rates are the render's: 96 kHz, 64-sample blocks. An increment of 1.0 x
the note's (inc_note) is the played note's frequency, 261.63 Hz at note 60.
  *_R          oscillator frequency / 261.63 Hz, Q14 (the base at note 60)
  dr_ktab[d]   the kick's pitch-sweep decay per block, Q15, for Sweep Time
               dial d: tau = 2 ms x 75^(d/127), 2 .. 150 ms
  dr_ftab[i]   a one-pole low-pass coefficient a = 1 - exp(-2 pi fc / fs),
               Q15, for fc = 300 Hz x (16000/300)^(i/127), 300 Hz .. 16 kHz
"""
import math, os

FS, BLK = 96000.0, 64
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'drum_tables.inc')

NOTE60 = 261.6256
q14 = lambda f: round(16384 * f / NOTE60)
KICK_HZ = 55.0                                    # the 909's ~50-60 Hz body
SN_HZ = 180.0                                     # the 909 snare's lower shell
HAT_HZ = (205.3, 304.4, 369.6, 522.7, 540.0, 800.0)   # the 808's six squares
SN_TAU = 0.015                                    # the snare's pitch drop

ktab = [round(32768 * math.exp(-BLK / (0.002 * 75 ** (d / 127) * FS))) for d in range(128)]
ftab = [round(32768 * (1 - math.exp(-2 * math.pi * 300 * (16000 / 300) ** (i / 127) / FS)))
        for i in range(128)]
assert all(a <= b for a, b in zip(ktab, ktab[1:])) and ktab[-1] < 32768
assert all(a < b for a, b in zip(ftab, ftab[1:])) and ftab[-1] < 32768
hats = [q14(f) for f in HAT_HZ]
assert max(hats) < 65536

L = ["",
     "| drum_tables.inc - generated by tools/gen_drum_tables.py. Do not edit.",
     f"KICK_R  = {q14(KICK_HZ)}          | {KICK_HZ} Hz at note 60, Q14",
     f"SN_R1   = {q14(SN_HZ)}         | {SN_HZ} Hz",
     f"SN_PEC  = {round(32768 * math.exp(-BLK / (SN_TAU * FS)))}         | the snare's pitch drop "
     f"a block, Q15 ({SN_TAU * 1000:.0f} ms)",
     "    .align 2",
     "dr_hat_r:                 | the 808's six squares, Q14: " +
     ", ".join(f"{f}" for f in HAT_HZ) + " Hz",
     "    .long " + ", ".join(map(str, hats)),
     "dr_ktab:                  | kick Sweep Time dial -> pitch decay a block, Q15"]
for i in range(0, 128, 8):
    L.append("    .long " + ", ".join(map(str, ktab[i:i + 8])))
L.append("dr_ftab:                  | 300 Hz .. 16 kHz -> one-pole coefficient, Q15")
for i in range(0, 128, 8):
    L.append("    .long " + ", ".join(map(str, ftab[i:i + 8])))
L.append("")
open(out, 'w').write("\n".join(L))
print(f"wrote {os.path.relpath(out)}")
